<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-QKEFB85" ignored="0" name="RetryFailedTest" tests="5" failures="1" timestamp="2022-09-28T08:09:42 IST" time="0.148" errors="0">
  <testcase name="test1" time="0.019" classname="New.Test002">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.002" classname="New.Test002">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.009" classname="New.Test002">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.003" classname="New.Test002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at New.Test002.test1(Test002.java:9)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.003" classname="New.Test002"/>
</testsuite> <!-- RetryFailedTest -->
